{% set name = "dagster_gcp" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: b4056710ba805f52f3fdb886407a9e0237623a81a567257f116a3c9ea6ed4d6f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - dagster
    - dagster_pandas
    - google-api-python-client
    - google-cloud-bigquery >=1.19
    - google-cloud-storage
    - google-resumable-media
    - oauth2client

test:
  imports:
    - dagster_gcp
    - dagster_gcp.bigquery
    - dagster_gcp.dataproc
    - dagster_gcp.gcs

about:
  home: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-gcp
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Package for GCP-specific Dagster framework solid and resource components.

extra:
  recipe-maintainers:
    - conda-forge/dagster
